USE CCUSTOMER;
SELECT COUNT(*) FROM CCUSTOMER_DATA
WHERE GENDER = 'K' OR DISTRICT ='MUTKÝ'

SELECT * FROM CCUSTOMER_DATA
ORDER BY BIRTHDATE ASC

SELECT CUSTOMERNAME,CITY, BIRTHDATE, DISTRICT, GENDER  
FROM CCUSTOMER_DATA
WHERE GENDER = 'K'
GROUP BY CUSTOMERNAME,CITY, BIRTHDATE, DISTRICT, GENDER
ORDER BY CITY ASC

USE OKUL_KUTUPHANESI;
SELECT * FROM KUTUPHANE
SELECT * FROM EMANET

SELECT E.EMANET_NO, (U.UYE_ADI+ ' ' + U.UYE_SOYADI) AS UYELER,
K.KUTUPHANE_ADI, E.ISBN, KI.KITAP_ADI, KI.YAYIN_TARIHI, E.EMANET_TARIHI
FROM EMANET E
JOIN KUTUPHANE K ON K.KUTUPHANE_NO = E.KUTUPHANE_NO
JOIN UYELER U ON U.UYE_NO = E.UYE_NO
JOIN KITAPLAR KI ON KI.ISBN = E.ISBN 
WHERE U.UYE_ADI LIKE 'HAKAN%'

USE CCUSTOMER
SELECT * FROM CCUSTOMER_DATA
WHERE CUSTOMERNAME LIKE '%ADA%' AND CUSTOMERNAME LIKE 'G%'

SELECT * FROM CCUSTOMER_DATA
WHERE BIRTHDATE BETWEEN   '1995-01-01' AND  '1999-01-01'

SELECT * FROM CCUSTOMER_DATA
WHERE 
 CITY IN ('Ýstanbul' ,'Ankara','Ýzmir')


