USE OKUL_KUTUPHANESI
SELECT * FROM EMANET
SELECT * FROM UYELER
SELECT * FROM KUTUPHANE
SELECT * FROM ADRESLER
SELECT * FROM KITAP_KUTUPHANE
SELECT * FROM KITAPLAR

INSERT INTO KITAPLAR
VALUES ('1234E5', 'VTYS', '2023-10-31', 500);

INSERT INTO KUTUPHANE 
VALUES ('Kayseri Üniversitesi', 'Devlet kütüphanesi',5);

USE OKUL_KUTUPHANESI
INSERT INTO EMANET 
VALUES ('1234E5',5,1,'2023-09-01','2023-10-01');
insert into uyeler 
VALUES ('BAHAULDDÝN','ALQARAGHULI','E','05358722002','bahaddin02kara@kayseri.edu.tr',5)
SELECT * FROM UYELER WHERE UYE_NO=1009
DELETE FROM UYELER WHERE UYE_NO=1009
INSERT INTO ADRESLER
VALUES('ORTA','KÖY',11,'KAYSERÝ',35,'TÜRKÝYE')
INSERT INTO UYELER
VALUES('FARUK','GENCYIGIT','E','654533','FSAFA@KAYSERI.EDU.TR',8)

SELECT * FROM UYELER WHERE UYE_NO=1016
DELETE FROM UYELER WHERE UYE_NO=1016